name: mcft
version: '1.0'
main: com.github.squi2rel.mcft.MCFT
api-version: '1.21'
authors: [ squi2rel ]
description: Face Tracking for Minecraft
website: github.com/squi2rel
commands:
  mcftreload:
    description: Reload config
    usage: /mcftreload
    permission: mcft.reload